services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Console Command

    App\Symfony\Command\QuotationSyncCommand:
        bind:
            App\Domain\Write\QuotationProvider: '@App\Infrastructure\QuotationProvider\QuotationProvider'
            SimpleBus\Message\Bus\MessageBus: '@SimpleBus\SymfonyBridge\Bus\CommandBus'

    # Controller

    App\Symfony\Controller\ConversionController:
        tags: ['controller.service_arguments']

    # Quotation Provider

    App\Infrastructure\QuotationProvider\ClientFactory: ~

    app.infrastructure.quotation_provider.http_client:
        class: 'GuzzleHttp\Client'
        factory: ['@App\Infrastructure\QuotationProvider\ClientFactory', 'create']

    app.infrastructure.quotation_provider.default_loader: ~

    App\Infrastructure\QuotationProvider\EcbLoader:
        bind:
            GuzzleHttp\ClientInterface: '@app.infrastructure.quotation_provider.http_client'
        tags:
            - { name: 'quotation_loader', alias: 'ecb' }

    App\Infrastructure\QuotationProvider\CbrLoader:
        bind:
            GuzzleHttp\ClientInterface: '@app.infrastructure.quotation_provider.http_client'
        tags:
            - { name: 'quotation_loader', alias: 'cbr' }

    App\Infrastructure\QuotationProvider\QuotationProvider:
        bind:
            App\Infrastructure\QuotationProvider\Loader: '@app.infrastructure.quotation_provider.default_loader'

    # Repository

    ### Write

    App\Infrastructure\Persistence\PersistedQuotationRepository:
        $class: 'App\Domain\Write\PersistedQuotation'

    ### Read

    App\Infrastructure\Persistence\QuotationRepository: ~

    # Application Handler

    ### Command

    App\Application\Command\RefreshHandler:
        bind:
            App\Domain\Write\PersistedQuotationRepository: '@App\Infrastructure\Persistence\PersistedQuotationRepository'
        tags:
            - { name: 'command_handler', handles: 'App\Application\Command\Refresh' }

    ### Query

    App\Application\Query\ConvertHandler:
        bind:
            App\Domain\Read\QuotationRepository: '@App\Infrastructure\Persistence\QuotationRepository'

