services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Console Command

    App\Symfony\Command\QuotationSyncCommand:
        bind:
            App\Domain\QuotationProvider: '@App\Infrastructure\QuotationProvider\QuotationProvider'
            SimpleBus\Message\Bus\MessageBus: '@SimpleBus\SymfonyBridge\Bus\CommandBus'

    # Controller

    App\Symfony\Controller\:
        resource: '../../../../App/Symfony/Controller/*'
        tags: ['controller.service_arguments']

    # Quotation Provider

    App\Infrastructure\QuotationProvider\ClientFactory: ~

    App\Infrastructure\QuotationProvider\HttpClient:
        class: 'App\Infrastructure\QuotationProvider\HttpClient'
        factory: ['@App\Infrastructure\QuotationProvider\ClientFactory', 'create']

    App\Infrastructure\QuotationProvider\DefaultLoader: ~ # see QuotationLoaderPass

    App\Infrastructure\QuotationProvider\EcbLoader:
        bind:
            GuzzleHttp\ClientInterface: '@App\Infrastructure\QuotationProvider\HttpClient'
        tags:
            - { name: 'quotation_loader', alias: 'ecb' }

    App\Infrastructure\QuotationProvider\CbrLoader:
        bind:
            GuzzleHttp\ClientInterface: '@App\Infrastructure\QuotationProvider\HttpClient'
        tags:
            - { name: 'quotation_loader', alias: 'cbr' }

    App\Infrastructure\QuotationProvider\QuotationProvider:
        bind:
            App\Infrastructure\QuotationProvider\Loader: '@App\Infrastructure\QuotationProvider\DefaultLoader'

    # Application Handler

    ### Refresh

    App\Application\RefreshHandler:
        tags:
            - { name: 'command_handler', handles: 'App\Application\Refresh' }

    ### Convert

    App\Application\ConvertHandler:
        tags:
            - { name: 'command_handler', handles: 'App\Application\Convert' }
