services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Console Command

    App\Symfony\Command\QuotationSyncCommand:
        bind:
            SimpleBus\Message\Bus\MessageBus: '@SimpleBus\SymfonyBridge\Bus\CommandBus'

    # Controller

    App\Symfony\Controller\:
        resource: '../../../../App/Symfony/Controller/*'
        tags: ['controller.service_arguments']

    # Quotation Provider

    App\Domain\QuotationProvider:
        bind:
            App\Infrastructure\QuotationLoader\Loader: '@App\Infrastructure\QuotationLoader\DefaultLoader'

    # Quotation Loader

    App\Infrastructure\QuotationLoader\ClientFactory:  ~

    App\Infrastructure\QuotationLoader\Client:
        class: 'App\Infrastructure\QuotationLoader\Client'
        factory: ['@App\Infrastructure\QuotationLoader\ClientFactory', 'create']

    App\Infrastructure\QuotationLoader\DefaultLoader: ~

    App\Infrastructure\QuotationLoader\EcbLoader:
        bind:
            GuzzleHttp\ClientInterface: '@App\Infrastructure\QuotationLoader\Client'
        tags:
            - { name: 'app.quotation_loader', alias: 'ecb' }

    App\Infrastructure\QuotationLoader\CbrLoader:
        bind:
            GuzzleHttp\ClientInterface: '@App\Infrastructure\QuotationLoader\Client'
        tags:
            - { name: 'app.quotation_loader', alias: 'cbr' }

    # Application Handler

    ### Refresh

    App\Application\RefreshHandler:
        tags:
            - { name: 'command_handler', handles: 'App\Application\Refresh' }

    ### Convert

    App\Application\ConvertHandler:
        tags:
            - { name: 'command_handler', handles: 'App\Application\Convert' }
