doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
        auto_mapping: true
        mappings:
            AppBundle:
                type: 'xml'
                is_bundle: false
                prefix: 'App\Domain\Write'
                dir: "%kernel.project_dir%/App/Infrastructure/Persistence/mapping/"
