version: "3"

services:
    cli:
        container_name: 'currency-rate-cli'
        depends_on:
            - percona
        build:
            context: .
            dockerfile: .docker/cli/Dockerfile
        links:
            - percona:mysql
        volumes:
            - .:/app

    percona:
        container_name: 'currency-rate-percona'
        image: percona:8.0.19-10
        ports:
            - "13306:3306"
        env_file:
            - .docker.env.prod
