version: "3"

services:
    cli:
        container_name: quotation-cli
        depends_on:
            - db
        build:
            context: .
            dockerfile: .docker/cli/Dockerfile
        links:
            - db:mysql
        volumes:
            - .:/app

    db:
        container_name: quotation-db
        image: percona:8.0.19-10
        ports:
            - 13306:3306
        env_file:
            - .docker.env.prod
        volumes:
            - ./.docker-volumes/db:/var/lib/mysql
