version: "3"

services:
    cli:
        container_name: quotation-cli
        depends_on:
            - db
            - db-test
        links:
            - db:mysql
            - db-test:mysql-test
        build:
            context: .
            dockerfile: .docker/cli/Dockerfile
        volumes:
            - .:/app

    db:
        container_name: quotation-db
        image: percona:5.7
        ports:
            - 13306:3306
        env_file:
            - .docker.env
        volumes:
            - ./.docker-volumes/db:/var/lib/mysql

    db-test:
        container_name: quotation-db-test
        image: percona:5.7
        ports:
            - 13307:3306
        env_file:
            - .docker.env.test
        volumes:
            - ./.docker-volumes/db-test:/var/lib/mysql

    server:
        container_name: quotation-server
        depends_on:
            - db
            - db-test
        links:
            - db:mysql
            - db-test:mysql-test
        build:
            context: .
            dockerfile: .docker/server/Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
