version: "3"

services:
    cli:
        container_name: 'currency-rate-cli'
        build:
            context: .
            dockerfile: .docker/cli/Dockerfile
        volumes:
            - .:/app


